"""
Django settings for DSTBundesliga project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['dstffbl.uber.space']

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'cms',
    'menus',
    'treebeard',
    'sekizai',
    'filer',
    'easy_thumbnails',
    'mptt',
    'djangocms_text_ckeditor',
    'djangocms_link',
    'djangocms_file',
    'djangocms_picture',
    'djangocms_video',
    'djangocms_googlemap',
    'djangocms_snippet',
    'djangocms_style',
    'django_tables2',
    'cookielaw',
    'DSTBundesliga.apps.leagues'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
]

ROOT_URLCONF = 'DSTBundesliga.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'DSTBundesliga.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGES = [
    ('en', 'English'),
    ('de', 'German'),
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CMS_TEMPLATES = [
    ('home.html', 'Home page template'),
]

CMS_PERMISSION = True

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.expanduser("~/html/media/")

THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.expanduser("~/html/static/")
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'staticfiles')]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

if os.getenv('DEV', 0) == '1':
    from local_settings import *

    STATIC_ROOT = os.path.join(BASE_DIR, "static/")
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'mydatabase',
        }
    }
else:
    # Database
    # https://docs.djangoproject.com/en/3.0/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'OPTIONS': {
                'read_default_file': os.getenv('DB_OPTIONS_FILE'),
            },
        }
    }

LEAGUES = {
    '527866518060916736': {
        'level': 1
    },
    '527869624503341056': {
        'level': 2
    },
    '527870366129315840': {
        'level': 2
    },
    '527870834605129728': {
        'level': 2
    },
    '527871479689084928': {
        'level': 2
    },
    '528220766650957824': {
        'level': 3
    },
    '528220929456033792': {
        'level': 3
    },
    '528221126048284672': {
        'level': 3
    },
    '528221276170813440': {
        'level': 3
    },
    '528221419296215040': {
        'level': 3
    },
    '528221584735494144': {
        'level': 3
    },
    '528221718451781632': {
        'level': 3
    },
    '528221864776589312': {
        'level': 3
    },
    '528223214189891584': {
        'level': 4
    },
    '528223699915460608': {
        'level': 4
    },
    '528224185712332800': {
        'level': 4
    },
    '528224602572652544': {
        'level': 4
    },
    "528224996306870272": {
        'level': 4
    },
    "528225405961195520": {
        'level': 4
    },
    "528225800340045824": {
        'level': 4
    },
    "541329171435925504": {
        'level': 4
    },
    "528226406906679296": {
        'level': 4
    },
    "528226873166483456": {
        'level': 4
    },
    "528227282366128128": {
        'level': 4
    },
    "528227650408763392": {
        'level': 4
    },
    "528228010767613952": {
        'level': 4
    },
    "528228381523116032": {
        'level': 4
    },
    "528228737048072192": {
        'level': 4
    },
    "528229069203394560": {
        'level': 4
    },
    "528229445851045888": {
        'level': 4
    },
    "528229807634931712": {
        'level': 4
    },
    "528230149584801792": {
        'level': 4
    },
    "528536236956430336": {
        'level': 4
    },
    "528536627353997312": {
        'level': 4
    },
    "535536010239815680": {
        'level': 4
    },
    "562932747744407552": {
        'level': 4
    },
    "565950891811397632": {
        'level': 4
    },
    "528537030585856000": {
        'level': 4
    },
    "528537483746848768": {
        'level': 4
    },
    "528537863235063808": {
        'level': 4
    },
    "528538249152942080": {
        'level': 4
    },
    "528947121228623872": {
        'level': 4
    },
    "528947538398294016": {
        'level': 4
    },
    "528948211777024000": {
        'level': 4
    },
    "528948552280461312": {
        'level': 4
    },
    "528948878882525184": {
        'level': 4
    },
    "528949253549862912": {
        'level': 4
    },
    "528949603166072832": {
        'level': 4
    },
    "528949988292710400": {
        'level': 4
    },
    "535536370404220928": {
        'level': 4
    }
}
