# Generated by Django 3.0.7 on 2021-04-24 11:22

import DSTBundesliga.apps.leagues.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leagues", "0027_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sleeper_id", models.CharField(max_length=50)),
                (
                    "region",
                    models.IntegerField(
                        choices=[
                            (1, "Nord"),
                            (2, "Ost"),
                            (3, "Süd"),
                            (4, "West"),
                            (5, "Ausland"),
                        ]
                    ),
                ),
                ("new_player", models.BooleanField(default=False)),
                (
                    "season",
                    models.ForeignKey(
                        default=DSTBundesliga.apps.leagues.models.Season.get_active,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="leagues.Season",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
