# Generated by Django 3.0.7 on 2021-05-01 17:39

from django.db import migrations


def load_news(apps, schema_editor):
    OldNews = apps.get_model('leagues', 'News')
    News = apps.get_model('dstffbl', 'News')
    for news in OldNews.objects.all():
        News.objects.create(
            title=news.title,
            content=news.content,
            image=news.image,
            date=news.date
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dstffbl', '0002_auto_20210501_1937'),
    ]

    operations = [
        migrations.RunPython(load_news),
    ]
