# Generated by Django 3.1 on 2021-07-25 07:38

from django.db import migrations


def assign_dst_players_to_season_users(apps, schema_editor):
    SeasonUser = apps.get_model('dstffbl', 'SeasonUser')
    DSTPlayer = apps.get_model('leagues', 'DSTPlayer')

    for su in SeasonUser.objects.all():
        try:
            player = DSTPlayer.objects.get(sleeper_id=su.sleeper_id)
        except DSTPlayer.DoesNotExist:
            player = DSTPlayer.objects.create(sleeper_id=su.sleeper_id)
        su.dst_player = player
        su.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dstffbl', '0007_seasonuser_dst_player'),
    ]

    operations = [
        migrations.RunPython(assign_dst_players_to_season_users),
    ]
