# Generated by Django 3.1 on 2021-07-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dstffbl', '0009_auto_20210725_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_username', models.CharField(max_length=50)),
                ('sleeper_league_name', models.CharField(max_length=100)),
                ('sleeper_league_id', models.CharField(max_length=50)),
                ('sleeper_league_link', models.CharField(max_length=500)),
                ('send_ts', models.DateTimeField(null=True)),
                ('has_erros', models.BooleanField(default=False)),
                ('error_message', models.CharField(max_length=500)),
                ('season_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dstffbl.seasonuser')),
            ],
        ),
    ]
