# Generated by Django 3.1.14 on 2022-07-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dstffbl", "0011_auto_20220720_1852"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonregistration",
            name="send_ts",
            field=models.DateTimeField(null=True),
        ),
    ]
