# Generated by Django 3.1.14 on 2022-07-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dstffbl", "0012_seasonregistration_send_ts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seasoninvitation",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="seasoninvitation",
            name="has_erros",
        ),
        migrations.RemoveField(
            model_name="seasoninvitation",
            name="send_ts",
        ),
        migrations.RemoveField(
            model_name="seasonregistration",
            name="send_ts",
        ),
        migrations.AddField(
            model_name="seasoninvitation",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
