# Generated by Django 3.1.14 on 2025-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dstffbl', '0018_auto_20230730_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dstemail',
            name='type',
            field=models.IntegerField(choices=[(1, 'CONFIRM_REGISTRATION'), (2, 'REGISTRATION_SUCCESSFUL'), (3, 'LEAGUE_INVITATION'), (4, 'PATREON_REQUEST')]),
        ),
    ]
