# Generated by Django 3.0.7 on 2020-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='fpts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='fpts_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='fpts_against_decimal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='fpts_decimal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='total_moves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='waiver_budget_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='waiver_position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roster',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
