# Generated by Django 3.0.7 on 2020-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20200806_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='type',
            field=models.IntegerField(choices=[(1, 'Player'), (2, 'Team')], default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='fantasy_positions',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='hashtag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sleeper_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
