# Generated by Django 3.0.7 on 2020-08-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_auto_20200806_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
