# Generated by Django 3.0.7 on 2020-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0011_news"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name_plural": "News"},
        ),
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
