# Generated by Django 3.0.7 on 2020-08-09 09:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0012_auto_20200809_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
