# Generated by Django 3.0.7 on 2020-08-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0013_auto_20200809_1141"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pick",
            name="user",
        ),
        migrations.AddField(
            model_name="pick",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picks",
                to="leagues.DSTPlayer",
            ),
        ),
    ]
