# Generated by Django 3.0.7 on 2020-10-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0021_auto_20201028_1933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statsweek",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="leagues.Player",
            ),
        ),
    ]
