# Generated by Django 3.0.7 on 2020-11-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_auto_20201107_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(default='dst_logo_96.png', max_length=255),
        ),
    ]
