# Generated by Django 3.0.7 on 2020-12-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0025_playoffmatchup"),
    ]

    operations = [
        migrations.AddField(
            model_name="playoffmatchup",
            name="rank",
            field=models.IntegerField(null=True),
        ),
    ]
