# Generated by Django 3.0.7 on 2021-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0026_playoffmatchup_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2021)),
                ("name", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
    ]
