# Generated by Django 3.1 on 2021-07-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0029_league_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-level', 'sleeper_name']},
        ),
    ]
