# Generated by Django 3.1.13 on 2021-10-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0035_waiverpickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiverpickup',
            name='changed_ts',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
