# Generated by Django 3.1.14 on 2022-07-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0036_auto_20211016_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
