# Generated by Django 3.1.14 on 2022-07-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0039_auto_20220727_2121"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finalseasonstanding",
            options={
                "ordering": [
                    "points_ranking_overall",
                    "points_ranking_on_level",
                    "points_ranking_in_league",
                ]
            },
        ),
        migrations.AlterField(
            model_name="finalseasonstanding",
            name="dst_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.dstplayer",
            ),
        ),
        migrations.AlterField(
            model_name="finalseasonstanding",
            name="points_ranking_in_league",
            field=models.IntegerField(default=0, verbose_name="#league"),
        ),
        migrations.AlterField(
            model_name="finalseasonstanding",
            name="points_ranking_on_level",
            field=models.IntegerField(default=0, verbose_name="#level"),
        ),
        migrations.AlterField(
            model_name="finalseasonstanding",
            name="points_ranking_overall",
            field=models.IntegerField(default=0, verbose_name="#overall"),
        ),
    ]
