# Generated by Django 3.1.14 on 2022-07-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0040_auto_20220728_2020"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finalseasonstanding",
            name="dst_player",
        ),
        migrations.AddField(
            model_name="finalseasonstanding",
            name="roster",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.roster",
            ),
        ),
    ]
