# Generated by Django 3.1.13 on 2023-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0041_auto_20220728_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="year",
            field=models.IntegerField(default=2023),
        ),
    ]
